/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CodeValueData
import org.openapitools.client.models.EnumOptionData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param tag 
 * @param transactionType 
 */


data class AccountingTagRuleData (

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "tag")
    val tag: CodeValueData? = null,

    @Json(name = "transactionType")
    val transactionType: EnumOptionData? = null

) {


}

