/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AppUser
import org.openapitools.client.models.Client

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param appUser 
 * @param client 
 * @param id 
 * @param new 
 */


data class AppUserClientMapping (

    @Json(name = "appUser")
    val appUser: AppUser? = null,

    @Json(name = "client")
    val client: Client? = null,

    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "new")
    val new: kotlin.Boolean? = null

) {


}

