/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hour 
 * @param minute 
 * @param nano 
 * @param second 
 */


data class java.time.LocalTime (

    @Json(name = "hour")
    val hour: kotlin.Int? = null,

    @Json(name = "minute")
    val minute: kotlin.Int? = null,

    @Json(name = "nano")
    val nano: kotlin.Int? = null,

    @Json(name = "second")
    val second: kotlin.Int? = null

) {


}

