/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import com.google.gson.annotations.SerializedName
import org.openapitools.client.models.EnumOptionData
import org.openapitools.client.models.RoleData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * PostAuthenticationResponse
 *
 * @param authenticated 
 * @param base64EncodedAuthenticationKey 
 * @param officeId 
 * @param officeName 
 * @param organisationalRole 
 * @param permissions 
 * @param roles 
 * @param staffDisplayName 
 * @param staffId 
 * @param userId 
 * @param username 
 */


data class PostAuthenticationResponse (

    @SerializedName("authenticated")
    val authenticated: kotlin.Boolean? = null,

    @SerializedName("base64EncodedAuthenticationKey")
    val base64EncodedAuthenticationKey: kotlin.String? = null,

    @SerializedName("officeId")
    val officeId: kotlin.Long? = null,

    @SerializedName("officeName")
    val officeName: kotlin.String? = null,

    @SerializedName("organisationalRole")
    val organisationalRole: EnumOptionData? = null,

    @SerializedName("permissions")
    val permissions: kotlin.collections.List<kotlin.String>? = null,

    @SerializedName("roles")
    val roles: kotlin.collections.List<RoleData>? = null,

    @SerializedName("staffDisplayName")
    val staffDisplayName: kotlin.String? = null,

    @SerializedName("staffId")
    val staffId: kotlin.Long? = null,

    @SerializedName("userId")
    val userId: kotlin.Long? = null,

    @SerializedName("username")
    val username: kotlin.String? = null

) {


}

