/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * PostAuthenticationRequest
 *
 * @param password 
 * @param username 
 */


data class PostAuthenticationRequest (

    @SerializedName("password")
    val password: kotlin.String,

    @SerializedName("username")
    val username: kotlin.String

) {


}

