/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CurrencyData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accountBalance 
 * @param availableBalance 
 * @param currency 
 * @param interestNotPosted 
 * @param interestPostedTillDate 
 * @param lastInterestCalculationDate 
 * @param prevInterestPostedTillDate 
 * @param runningBalanceOnInterestPostingTillDate 
 * @param runningBalanceOnPivotDate 
 * @param totalAnnualFees 
 * @param totalDeposits 
 * @param totalFeeCharge 
 * @param totalInterestEarned 
 * @param totalInterestPosted 
 * @param totalOverdraftInterestDerived 
 * @param totalPenaltyCharge 
 * @param totalWithdrawalFees 
 * @param totalWithdrawals 
 * @param totalWithholdTax 
 */


data class SavingsAccountSummaryData (

    @Json(name = "accountBalance")
    val accountBalance: java.math.BigDecimal? = null,

    @Json(name = "availableBalance")
    val availableBalance: java.math.BigDecimal? = null,

    @Json(name = "currency")
    val currency: CurrencyData? = null,

    @Json(name = "interestNotPosted")
    val interestNotPosted: java.math.BigDecimal? = null,

    @Json(name = "interestPostedTillDate")
    val interestPostedTillDate: java.time.LocalDate? = null,

    @Json(name = "lastInterestCalculationDate")
    val lastInterestCalculationDate: java.time.LocalDate? = null,

    @Json(name = "prevInterestPostedTillDate")
    val prevInterestPostedTillDate: java.time.LocalDate? = null,

    @Json(name = "runningBalanceOnInterestPostingTillDate")
    val runningBalanceOnInterestPostingTillDate: java.math.BigDecimal? = null,

    @Json(name = "runningBalanceOnPivotDate")
    val runningBalanceOnPivotDate: java.math.BigDecimal? = null,

    @Json(name = "totalAnnualFees")
    val totalAnnualFees: java.math.BigDecimal? = null,

    @Json(name = "totalDeposits")
    val totalDeposits: java.math.BigDecimal? = null,

    @Json(name = "totalFeeCharge")
    val totalFeeCharge: java.math.BigDecimal? = null,

    @Json(name = "totalInterestEarned")
    val totalInterestEarned: java.math.BigDecimal? = null,

    @Json(name = "totalInterestPosted")
    val totalInterestPosted: java.math.BigDecimal? = null,

    @Json(name = "totalOverdraftInterestDerived")
    val totalOverdraftInterestDerived: java.math.BigDecimal? = null,

    @Json(name = "totalPenaltyCharge")
    val totalPenaltyCharge: java.math.BigDecimal? = null,

    @Json(name = "totalWithdrawalFees")
    val totalWithdrawalFees: java.math.BigDecimal? = null,

    @Json(name = "totalWithdrawals")
    val totalWithdrawals: java.math.BigDecimal? = null,

    @Json(name = "totalWithholdTax")
    val totalWithholdTax: java.math.BigDecimal? = null

) {


}

